name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build for Windows
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows]
        arch: [amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        env:
          GOOS: windows
          GOARCH: amd64
          CGO_ENABLED: 0
        run: |
          OUTPUT="closeMonitorByHttp-windows-amd64.exe"
          go build -ldflags="-s -w -H=windowsgui" -o $OUTPUT
          mkdir -p dist
          mv $OUTPUT dist/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: dist/

  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        run: |
          tags=($(git tag --sort=-v:refname))
          current_tag="${{ github.ref_name }}"
          previous_tag=""
          
          for i in "${!tags[@]}"; do
            if [[ "${tags[i]}" == "$current_tag" ]]; then
              if [[ $i -lt $((${#tags[@]} - 1)) ]]; then
                previous_tag="${tags[i+1]}"
              fi
              break
            fi
          done
          
          if [ -z "$previous_tag" ]; then
            echo "No previous tag found, using initial commit"
            git log --pretty=format:"- %s" > changelog.md
          else
            echo "Generating changes between $previous_tag and $current_tag"
            git log --pretty=format:"- %s" $previous_tag..$current_tag > changelog.md
          fi

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body_path: changelog.md
          files: |
            dist/closeMonitorByHttp-*
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_TOKEN }}